// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA70DQg1OFeX-MExy7ePB2gcZDHuLx0rNQ',
    appId: '1:992587215094:web:7594bc3afa339bb78f3cd7',
    messagingSenderId: '992587215094',
    projectId: 'redawn-60f80',
    authDomain: 'redawn-60f80.firebaseapp.com',
    storageBucket: 'redawn-60f80.firebasestorage.app',
    measurementId: 'G-WNX7CFH90M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDMgN3NYjjrQj8zfrDN8MXU3Z8rFrSn6Q',
    appId: '1:992587215094:android:007859f2e9e530f98f3cd7',
    messagingSenderId: '992587215094',
    projectId: 'redawn-60f80',
    storageBucket: 'redawn-60f80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL7Qcd5bgde2gEteVV4lM8_Wo3l6ymYVo',
    appId: '1:992587215094:ios:fcf36872b66259058f3cd7',
    messagingSenderId: '992587215094',
    projectId: 'redawn-60f80',
    storageBucket: 'redawn-60f80.firebasestorage.app',
    iosBundleId: 'com.example.redawn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA70DQg1OFeX-MExy7ePB2gcZDHuLx0rNQ',
    appId: '1:992587215094:web:6e6822ec9e3716ef8f3cd7',
    messagingSenderId: '992587215094',
    projectId: 'redawn-60f80',
    authDomain: 'redawn-60f80.firebaseapp.com',
    storageBucket: 'redawn-60f80.firebasestorage.app',
    measurementId: 'G-P74PRV8FP3',
  );
}
